### ISSUE TITLE
Подготовить спрайты врагов

### ISSUE THREAD

**Issue by DrStarland** [DrStarland/teamwork#10]
Нарисовать последовательность спрайтов, которые лягут в основу анимации, для:
а) патрулирующего врага ближнего боя (!_!);
б)  неразрушаемого врага-препятствия с ближним уроном (лезвие или колючка);
в) разрушаемого врага-препятствия (блок-колючка).

**Comment by mireyn** [comment]
вот они по порядку...
![theExclamationer](https://user-images.githubusercontent.com/66076194/163288435-dd2c2b85-b456-4982-a0ac-df76439cbef0.png)
![Trap_002](https://user-images.githubusercontent.com/66076194/163288463-9feda6bb-5d5f-4336-8dd1-02f5aeeb0a5b.png)
![BreakableTrap_002](https://user-images.githubusercontent.com/66076194/163288474-1f1d62b3-3bbb-4952-b1ac-8f33571d5e39.png)
