### ISSUE TITLE
Реализовать главное меню

### ISSUE THREAD

**Issue by DrStarland** [DrStarland/teamwork#11]
В соответствии с [диаграммой состояний](https://github.com/DrStarland/teamwork/wiki/%D0%94%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B-%D0%B8-%D1%81%D1%85%D0%B5%D0%BC%D1%8B) создать сцену с кнопками-переходами на соответствующие сцены

**Comment by mireyn** [comment]
и в соответствии с [этими макетами](https://github.com/DrStarland/teamwork/tree/master/materials/maquette)

для этого нужно сначала выполнить #13.

**Comment by mireyn** [comment]
#13 выполнено, можно приступать к реализации.

**Comment by DrStarland** [comment]
Залил вместе с заглушкой выбора уровня и страницей об авторах
