### ISSUE TITLE
Создать макет экранов игры

### ISSUE THREAD

**Issue by mireyn** [DrStarland/teamwork#2]
Нарисовать несколько изображений, на основе которых будет строиться интерфейс непосредственно игры (уровней) и её вспомогательных экранов.
На отдельных изображениях:

- [x] Главное меню
- [x] Страница меню "Об авторах"
- [x] Меню выбора уровня
- [x] Общий вид уровня

**Comment by DrStarland** [comment]
Нарисован прототип игрового процесса

**Comment by mireyn** [comment]
Добавлены остальные прототипы, задача выполнена.
