### ISSUE TITLE
Создать префабы для повторяющихся объектов

### ISSUE THREAD

**Issue by mireyn** [DrStarland/teamwork#27]
Необходимо создать [префабы](https://docs.unity3d.com/ru/530/Manual/Prefabs.html) для создания экземпляров хранимых объектов в сцене.
Конкретно для:
- "Фаерболлов" (оружие игрока)
- "Антифаерболлов" (оружие врагов)
- Наборов объектов, реализующих здоровье игрока и врага
- Настроек
- Игрового менеджера сцены

**Comment by DrStarland** [comment]
Я бы назвал это шаблоном объекта

**Comment by mireyn** [comment]
спасибо, ваше мнение очень важно для нас

**Comment by DrStarland** [comment]
Моё мнение выражено в коммите [0fa19f9](https://github.com/DrStarland/teamwork/commit/0fa19f948595738b345cc0ae6df5e7a895485b25)
