### ISSUE TITLE
Подготовить спрайты игрового персонажа

### ISSUE THREAD

**Issue by DrStarland** [DrStarland/teamwork#8]
Необходимо нарисовать анимации ходьбы, ожидания и прыжка для разработанного персонажа (Вопросца)

**Comment by DrStarland** [comment]
Концептуальный спрайт ходьбы...
![Безымянный](https://user-images.githubusercontent.com/66081492/162285613-0ef5f09d-1778-46bb-a4e3-b199cd8b1ce3.png)
.

**Comment by mireyn** [comment]
сделано, ожидает слияния в мастер.
